const  Car = {
    first_name: null,
    last_name: null,
    car_company: null,
    phone: null,
    pickup_address1: null,
    pickup_address2: null,
    pickup_city_name: null,
    pickup_city_code: null,
    pickup_admin_code: null,
    pickup_country: null,
    pickup_zip: null,
    pickup_datetime: null,
    pickup_time_zone: null,
    pickup_time_zone_id: null,
    dropoff_address1: null,
    dropoff_address2: null,
    dropoff_city_name: null,
    dropoff_city_code: null,
    dropoff_admin_code: null,
    dropoff_country: null,
    dropoff_zip: null,
    dropoff_datetime: null,
    dropoff_time_zone: null,
    dropoff_time_zone_id: null,
    car_notes: null,
    confirmation_no: null,
    price: null,
    currency: null
}

export default Car;



//
// CREATE TABLE "Traxo-parser".dbo.Car
// (id int NOT NULL,
//     first_name varchar(25) NOT NULL,
//     last_name varchar(25) NOT NULL,
//     car_company varchar(25) NOT NULL,
//     phone varchar(25),
//     pickup_address1 varchar(25),
//     pickup_address2 varchar(25),
//     pickup_city_name varchar(25),
//     pickup_city_code varchar(25),
//     pickup_country varchar(25),
//     pickup_zip varchar(25),
//     pickup_datetime datetime,
//     pickup_time_zone varchar(25),
//     pickup_time_zone_id varchar(25),
//     checkout_time_zone varchar(25),
//     dropoff_address1 varchar(25),
//     dropoff_address2 varchar(25),
//     dropoff_city_name varchar(25),
//     dropoff_city_code varchar(25),
//     dropoff_admin_code varchar(25),
//     dropoff_country varchar(25),
//     dropoff_zip varchar(25),
//     dropoff_datetime datetime,
//     dropoff_time_zone varchar(25),
//     dropoff_time_zone_id varchar(25),
//     price float,
//     currency varchar(25),
//     confirmation_no varchar(25) NOT NULL,
//     car_notes varchar(25),
//     PRIMARY KEY (id))
